#!/bin/bash


#keywords: pypi .pypirc twine setuptools


PARAMIZED="$1"


PKGDEFAULT="my_pkg"

bettercand=$(pwd|grep pypi)

if [[ ! -z $bettercand ]]; then
    PKGDEFAULT=$(basename "$bettercand" | cut -d '.' -f 1)
fi

skeleton_pypi() {
    P=$1
    U=turbobert
    FULLNAME="Robert Degen"
    FULLMAIL="turbodev@mailbox.org"
    mkdir $P
    mkdir $P/src
    mkdir $P/src/${P}
    mkdir $P/tests
    echo TODO >$P/LICENSE
    echo TODO >$P/README.md
    cat >$P/Makefile <<EOF
build:
$(echo -en "\t")\${HOME}/bin/vp -m build

setup:
$(echo -en "\t")\${HOME}/bin/vp -m pip install --upgrade build
$(echo -en "\t")\${HOME}/bin/vpip install twine

upload:
$(echo -en "\t")\${HOME}/bin/vp -m twine upload dist/*
EOF

    cat >$P/pyproject.toml <<EOF
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "${P}"
version = "0.0.1"
authors = [
  { name="$FULLNAME", email="$FULLMAIL" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "reportlab"
]

[project.urls]
Homepage = "https://github.com/turbo-bert"
Issues = "https://github.com/turbo-bert"

EOF

}



if [[ ! -z $PARAMIZED ]]; then
    echo "got $PARAMIZED"
    skeleton_pypi $PARAMIZED
    exit 0
fi

while true; do
    exec 3>&1
    X=$(dialog --menu "PyPI Prepper - Main Menu" 0 0 0 new "Create New Project" quit "Quit Now" 2>&1 1>&3)
    Y=$?
    exec 3>&-
    if [[ $Y = 0 ]]; then
        if [[ $X = quit ]]; then
            exit 0
        fi
        if [[ $X = new ]]; then
            exec 3>&1
            N=$(dialog --inputbox "Package Name (identifier)" 0 0 $PKGDEFAULT 2>&1 1>&3)
            Y=$?
            exec 3>&-

            exec 3>&1
            NCONFIRM=$(dialog --yesno "Is [$N] correct?" 0 0 2>&1 1>&3)
            Y=$?
            exec 3>&-

            #dialog --msgbox "$NCONFIRM/$Y" 0 0
            if [[ $Y = 0 ]]; then
                skeleton_pypi $N
                dialog --msgbox "Done" 0 0
            fi
        fi
    else
        exit 0
    fi
done
