#!/bin/bash


which jq 1>/dev/null 2>/dev/null
jq_ok=$?


if [[ ! $jq_ok = "0" ]]; then
    echo "'jq' is not in your PATH."
    echo "make sure it is installed!"
    exit 1
fi



(
echo "["
(
docker ps --format json
#docker ps --format json | tr '\n' ',' | gsed -E 's/,$//g'
    ) | jq "{ID,Image}" | tr '\n' '\t' | gsed -E 's|\}\t\{|\}\t\,\{|g' | tr '\t' '\n'
echo "]"
) | jq -r '.[] | (.ID+" "+.Image)' | tr '\n' ' ' >/tmp/containerlist



which dialog 1>/dev/null 2>/dev/null
dialog_ok=$?


if [[ ! $dialog_ok = "0" ]]; then
    echo "'dialog' is not in your PATH."
    echo "make sure it is installed! for example run:"
    echo "apt update && apt install -y dialog"
    exit 1
fi

uname | grep -i darwin >/dev/null 2>/dev/null
mactest=$?
CMD_SED=sed
if [[ $mactest = 0 ]]; then
    CMD_SED=gsed
fi

exec 3>&1
X=$(dialog --menu "Log follow container..." 0 0 0 `cat /tmp/containerlist` 2>&1 1>&3)
Y=$?
exec 3>&-
if [[ $Y = "0" ]]; then
    set -x
    docker logs -f $X
fi
