#!/bin/bash



uname | grep -i darwin >/dev/null 2>/dev/null
mactest=$?
CMD_SED=sed
if [[ $mactest = 0 ]]; then
    CMD_SED=gsed
fi

exec 3>&1
X=$(dialog --menu "Exec root sh in container..." 0 0 0 `docker ps --format 'table {{.ID}}\t{{.Names}}_{{.Image}}_{{.Ports}}' | $CMD_SED -E 's/ /\t/' | tr ' ' '_' | tr '\t' ' ' | tail -n +2` 2>&1 1>&3)
Y=$?
exec 3>&-
if [[ $Y = "0" ]]; then
    docker exec -it $X /bin/sh
fi
