#!/bin/bash


# deb bauer
IMG="turbobert/debauer$1:latest"

if [[ ! $1 = 22 ]]; then
    if [[ ! $1 = 24 ]]; then
        if [[ ! $1 = 26 ]]; then
            echo "Invalid docker image $IMG" 1>&2
            exit 1
        fi
    fi
fi

docker pull --platform linux/amd64 $IMG

D=`pwd`




echo -n "Press ENTER to run $IMG in $D or CTRL-C to abort..."
read

if [[ $2 = i ]]; then
    docker run     --platform linux/amd64              --rm -v "$D:/work" -it $IMG /bin/bash
    exit 0
else
    docker run     --platform linux/amd64              --rm -v "$D:/work" -it $IMG
fi
